# Support for (EMEA/EU-based) Honeywell TCC climate systems.
# Describes the format for available services

set_system_mode:
  fields:
    mode:
      example: Away
      selector:
        select:
          options:
            - "Auto"
            - "AutoWithEco"
            - "Away"
            - "Custom"
            - "DayOff"
            - "HeatingOff"
    period:
      example: '{"days": 28}'
      selector:
        object:
    duration:
      example: '{"hours": 18}'
      selector:
        object:

reset_system:

refresh_system:

set_zone_override:
  target:
    entity:
      integration: evohome
      domain: climate
  fields:
    setpoint:
      required: true
      selector:
        number:
          min: 4.0
          max: 35.0
          step: 0.1
    duration:
      example: '{"minutes": 135}'
      selector:
        object:

clear_zone_override:
  target:
    entity:
      integration: evohome
      domain: climate
